version: '3'

services:
  node1:
    build:
      context: .
    ports:
      - 8090:8090

  node2:
    build:
      context: .
    ports:
      - 8091:8090

  node3:
    build:
      context: .
    ports:
      - 8093:8090

